update_delay: 1800 # Update every n seconds
arduino_uuid: a_uuid
iot_secret: a_secret

digital_pins:
    red_led: 6
    relay: 5

analog_pins:
    hygrometer: 5

wifi:
    ssid: your_ssid
    password: your_password

sensor_hub:
    ip: ip_or_domain
    port: 80
