update_delay: 1800 # Update every n seconds
arduino_uuid: a_uuid

digital_pins:
    green_led: 6
    relay: 2
    dht_11: 4

analog_pins:
    rain_detector: 7

wifi:
    ssid: your_ssid
    password: your_password

sensor_hub:
    ip: ip_or_domain
    port: 80
