-
  name: Veg lights
  gpio_bcm_pins: [24, 27]
  start_at: '5:0:0'
  run_for: '19:0:0'

-
  name: Bloom lights
  gpio_bcm_pins: [23]
  start_at: '8:0:0'
  run_for: '12:0:0'

-
  name: Fan system 1
  gpio_bcm_pins: [22]
  start_at: '5:0:0'
  run_for: '0:5:0'
  repeat_every: '1:0:0'

-
  name: Fan system 2
  gpio_bcm_pins: [25]
  start_at: '5:5:0'
  run_for: '0:5:0'
  repeat_every: '1:0:0'
