hygrometer_pins: [3, 2, 1, 0] # Analog pins
photocell_pins: [7] # Analog pins
dht11_pins: [5, 6] # Digital pins

update_delay: 1800 # Update every n seconds
arduino_uuid: a_uuid
iot_secret: a_secret

digital_pins:
    relay: 4
    red_led: 5
    green_led: 6

esp_board: # Digital pins
    rx: 11
    tx: 10

wifi:
    ssid: your_ssid
    password: your_password

sensor_hub:
    ip: ip_or_domain
    port: 80
